language: python
python:
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - TEST_STYLE=1
  - TEST_STYLE=0
install:
# everything else
- "travis_retry pip install . --only-binary=:all:"
# coverage packages
- travis_retry pip install coverage coveralls
- pip freeze
script:
- coverage run --source=qpimage ./setup.py test
- coverage report -m
after_success:
- coveralls --verbose
