language: python
python:
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - TEST_STYLE=1
  - TEST_STYLE=0
install:
# everything else
- travis_retry pip install .
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- if [ "${TEST_STYLE}" == "1" ]; then
       coverage run --source=dclab ./setup.py test;
       coverage report -m;
       codecov;
  else
       flake8 qpimage;
       flake8 tests --ignore E402;
  fi;
after_success:
- codecov
